name: Build
on: ['push', 'pull_request']

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node: [ '18', '20', '22' ]
      name: Node ${{ matrix.node }}
      steps:
        - uses: actions/checkout@v4

        - name: Setup node
          uses: actions/setup-node@v4.0.3
          with:
            node-version: ${{ matrix.node }}

        - name: Install dependencies
          run: npm ci

        # - name: Initialize CodeQL
        #   uses: github/codeql-action/init@v1
        #   with:
        #     languages: javascript
            
        - name: Execute tests
          run: npm test
            
        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          if: github.actor != 'dependabot[bot]'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        # - name: Perform CodeQL Analysis
        #   uses: github/codeql-action/analyze@v1